databaseChangeLog:
  - changeSet:
      id: table-tasks
      author: SmirnovDY
      changes:
        - createTable:
            tableName: tasks
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    primaryKeyName: task_id
                    nullable=: false
              - column:
                  name: id_project
                  type: INT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_id_project()
                    references: projects(id)
              - column:
                  name: task_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: task_description
                  type: TEXT
              - column:
                  name: deadline
                  type: DATE
              - column:
                  name: status
                  type: VARCHAR(50)